### ISSUE TITLE
Nueva librería SuitEtecsa SDK Kotlin

### ISSUE THREAD

**Issue by lesclaz** [applifycu/simple#27]
[Esta](https://github.com/suitetecsa/sdk-kotlin) es la nueva lib que hice, te hará mejorar mucho el código. Por ejemplo:
Mira como quedaría la función loadCaptcha.

__Antes__:
https://github.com/applifycu/simple/blob/2eeb64ccf1bd795c681dfc9432c01e9422965d14/app/src/main/java/com/arr/simple/utils/Nauta/NautaLogin.java#L113-L133

__Después__:

```kotlin
public void loadCaptcha(ImageView imageCaptcha) {
     api.getCaptchaImage()
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(byteArray -> {
            imageCaptcha.setImageBitmap(BitmapFactory.decodeByteArray(byteArray, 0, byteArray.length)); 
        }, error -> {
            // Maneja el error
        });
 } 
```

Obviamente no es solo cambiar la función, tendrias que migrar a la nueva lib, pero es algo bastante sencillo.
A parte de agregar la nueva lib como dependencia tambien tendras que agregar esta
```kotlin
implementation("io.reactivex.rxjava3:rxandroid:3.0.2")
```

**Comment by esalessandrxx** [comment]
> [Esta](https://github.com/suitetecsa/sdk-kotlin) es la nueva lib que hice, te hará mejorar mucho el código. Por ejemplo: Mira como quedaría la función loadCaptcha.
> 
> **Antes**:
> 
> https://github.com/applifycu/simple/blob/2eeb64ccf1bd795c681dfc9432c01e9422965d14/app/src/main/java/com/arr/simple/utils/Nauta/NautaLogin.java#L113-L133
> 
> **Después**:
> 
> ```kotlin
> public void loadCaptcha(ImageView imageCaptcha) {
>      api.getCaptchaImage()
>         .observeOn(AndroidSchedulers.mainThread())
>         .subscribe(byteArray -> {
>             imageCaptcha.setImageBitmap(BitmapFactory.decodeByteArray(byteArray, 0, byteArray.length)); 
>         }, error -> {
>             // Maneja el error
>         });
>  } 
> ```
> 
> Obviamente no es solo cambiar la función, tendrias que migrar a la nueva lib, pero es algo bastante sencillo. A parte de agregar la nueva lib como dependencia tambien tendras que agregar esta
> 
> ```kotlin
> implementation("io.reactivex.rxjava3:rxandroid:3.0.2")
> ```

Gracias por avisarme, deja ver si hago un time para empezar a migrar.
